var lv_lang = {
    whatWeDoTitle: "Par mums",
    whatWeDoText1: "Mūsu organizācija ir dibināta 2005. gada aprīla mēnesī, kā ģimenes uzņēmums, šos gadus atsauksmes par mums ir bijušas labas un cenšamies pēc iespējas ieviest savā darbā jaunievedumus un paplašināt darba iespējas un darbības sfēras. Uzlabot tehniku un veidot savu darbu pieejamāku un izdevīgāku pasūtītājiem.",
    whatWeDoText2: "Mūsu darba sfēra šobrīt ir celtniecības atkritumu izvešana, to savākšana ar iekrāvējiem, dažādu tilpumu konteineru noma, BoBcata noma, kā ārī veicam darbus ar teleskopiskā iekrāvēja palīdzību.",
    contact: "Kontakti",
    order: "Тālrunis pasūtijumiem",
    agreement: "Tālrunis līgumu slēgšanai",
    juris: "Juris",
    angela: "Anželika",
    email: "E-pasts",
    services: "Pakalpojumi",
    containerRent: "Konteineru noma",
    prices: "Cenas",
    area: "Rajons",
    priedaine: "Priedaine",
    lielupe: "Lielupe - Jaundubulti",
    pumpuri: "Pumpri - Vaivari",
    kauguri: "Kauguri, Sloka",
    kemeri: "Ķemeri",
    lapmezciems: "Lapmežciems",
    bigaunciems: "Bigaunciems",
    ragaciems: "Ragaciems"
};