var lv_lang = {
    whatWeDoTitle: "Par mums",
    whatWeDoText1: "Mūsu organizācija ir dibināta 2005. gada aprīļa mēnesī, kā ģimenes uzņēmums. Šos gadus atsauksmes par mums ir bijušas labas un cenšamies pēc iespējas ieviest savā darbā jaunievedumus un paplašināt darba iespējas un darbības sfēras, uzlabot tehniku un veidot savu darbu pieejamāku un izdevīgāku pasūtītājiem.",
    whatWeDoText2: "Mūsu darba sfēra šobrīd ir celtniecības atkritumu izvešana, to savākšana ar iekrāvējiem, dažādu tilpumu konteineru noma, kā arī veicam darbus ar teleskopiskā iekrāvēja palīdzību.",
    contact: "Kontakti",
    order: "Тālrunis pasūtijumiem",
    agreement: "Tālrunis līgumu slēgšanai",
    juris: "Juris",
    angela: "Anželika",
    email: "E-pasts",
    services: "Pakalpojumi",
    containerRent: "Konteineru noma",
    man4o4Rent: "MAN 4X4 pakalpojumi",
    loaderRent: "Iekrāvēja JCB 520-40 pakalpojumi",
    prices: "Cenas",
    area: "Rajons",
    priedaine: "Priedaine",
    lielupe: "Lielupe - Jaundubulti",
    pumpuri: "Pumpri - Vaivari",
    kauguri: "Kauguri, Sloka",
    kemeri: "Ķemeri",
    lapmezciems: "Lapmežciems",
    bigaunciems: "Bigaunciems",
    ragaciems: "Ragaciems",
    others: "Citi rajoni",
    onAgreement: "Pēc vienošanās.",
    pricesArea: "Izmaksas saistītas ar konteineru izvešanu no rajoniem (bez PVN)."
};